CREATE DATABASE ADPEnrollmentSystem;
USE ADPEnrollmentSystem;

CREATE TABLE EMPLOYEE
(
EmpID VARCHAR(50) PRIMARY KEY,
FName VARCHAR(50),
MName VARCHAR(50),
LName VARCHAR(50),
EmpType  VARCHAR(50),
EmpStatus VARCHAR(50)
);

SELECT * FROM EMPLOYEE
SELECT * FROM USERS
DROP TABLE EMPLOYEE
INSERT INTO EMPLOYEE VALUES('10001','Rent','Santos','Manisalyo','Registrar','ACTIVE');


CREATE TABLE USERS (
Username VARCHAR(50) FOREIGN KEY REFERENCES EMPLOYEE(EmpID),
Password varchar(50));

SELECT * FROM USERS
INSERT INTO USERS VALUES('10001','123');

CREATE TABLE UserLoginHistory
(
Username VARCHAR(50) FOREIGN KEY REFERENCES EMPLOYEE(EmpID),
LoginDate varchar(50),
LoginTime varchar(50));

SELECT * FROM UserLoginHistory
DROP TABLE UserLoginHistory

SELECT EmpID, FName,MName,LName  FROM EMPLOYEE WHERE EmpID = 10001

SELECT USERS.Username, USERS.Password FROM USERS WHERE EmpID = 10001

SELECT USERS.Username FROM USERS WHERE USERS.Username = 10001 
